### ISSUE TITLE
How to find support for older version of Unreal?

### ISSUE THREAD

**Issue by robb-uprising** [aws/amazon-gamelift-plugin-unreal#54]
I'm wondering if there is a repo for Unreal Versions pre-5? I'm using 4.25 and am having trouble locating a Gamelift plugin for that version.

**Comment by fzehao** [comment]
Hi, now there's no visual plugins for UE4 like this one, but you can use the lightweight plugin for UE4: 
Go to https://aws.amazon.com/gamelift/getting-started-sdks/, expand the C++ section of the server SDK, and download C++ Server SDK Plugin for Unreal

**Comment by fzehao** [comment]
However we did receive reports that this plugin works for UE4.27: https://github.com/aws/amazon-gamelift-plugin-unreal/issues/18, you could try it out
